version = 0.1
[default.deploy.parameters]
stack_name = "sam-fetch-news-content-module"
resolve_s3 = true
s3_prefix = "sam-fetch-news-content-module"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
